import sanitizeHtml from 'sanitize-html'

const allowedTags = [
  'a',
  'abbr',
  'article',
  'aside',
  'b',
  'blockquote',
  'br',
  'caption',
  'cite',
  'code',
  'dd',
  'del',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'ins',
  'kbd',
  'li',
  'mark',
  'ol',
  'p',
  'pre',
  'q',
  's',
  'samp',
  'section',
  'small',
  'span',
  'strong',
  'sub',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'u',
  'ul',
  'var',
] as const

/**
 * Book files are untrusted input. Keep only inert, reader-relevant markup before
 * content is sent to the renderer or inserted into a DOM measurement container.
 */
export const sanitizeBookHtml = (html: string): string =>
  sanitizeHtml(html, {
    allowedTags: [...allowedTags],
    allowedAttributes: {
      '*': ['class', 'dir', 'id', 'lang', 'title'],
      a: ['href'],
      img: ['alt', 'height', 'src', 'width'],
      ol: ['start', 'type'],
      td: ['colspan', 'rowspan'],
      th: ['colspan', 'rowspan', 'scope'],
    },
    allowedSchemes: ['http', 'https'],
    allowedSchemesByTag: {
      img: ['data'],
    },
    allowProtocolRelative: false,
    disallowedTagsMode: 'discard',
    enforceHtmlBoundary: true,
    nonTextTags: ['script', 'style', 'textarea', 'title', 'xmp'],
    parseStyleAttributes: false,
  }).trim()
