/**
 * WASM Reader Service
 * TypeScript wrapper for the Rust/WASM reader module
 */

import { BookContent } from '@app-types/reader.types'
import {
  DEFAULT_READER_FONTS,
  FontToLoad,
  WasmLoadBookResult,
  WasmPageChapter,
  WasmPaginationResult,
  WasmReaderSettings,
  WasmSearchResult,
  WasmSettingsUpdateResult,
  WASM_THEME_COLORS,
  WasmThemeName,
} from '../types/wasm-reader.types'
import { ReaderSettings, ReaderTheme } from '../store/useReaderSettingsStore'

/**
 * Selection result
 */
export interface WasmSelectionResult {
  startIndex: number
  endIndex: number
  text: string
  chapterId: string
}

/**
 * Selection rectangle
 */
export interface WasmSelectionRect {
  x: number
  y: number
  width: number
  height: number
}

// WASM module types (will be generated by wasm-pack)
interface WasmModule {
  init: () => void
  load_font: (name: string, data: Uint8Array) => void
  update_settings: (settingsJson: string) => WasmSettingsUpdateResult
  load_book: (bookContentJson: string) => WasmLoadBookResult
  paginate: (width: number, height: number) => WasmPaginationResult
  render_page: (pageIndex: number, width: number, height: number) => Uint8Array
  get_page_chapter: (pageIndex: number) => WasmPageChapter
  search_text: (query: string) => WasmSearchResult[]
  unload_book: () => void
  get_settings: () => WasmReaderSettings
  // Selection API
  selection_start: (x: number, y: number) => void
  selection_update: (x: number, y: number) => void
  selection_end: () => WasmSelectionResult | null
  selection_clear: () => void
  get_selection_rects: () => WasmSelectionRect[]
  get_selected_text: () => string | null
  get_link_at_position: (pageIndex: number, x: number, y: number) => string | null
  // Performance API
  prerender_pages: (currentPage: number, width: number, height: number, range: number) => void
  get_pagination_stats: () => { hasDocument: boolean; isPaginated: boolean; totalChapters: number; totalPages: number }
  clear_render_cache: () => void
}

let wasmModule: WasmModule | null = null
let initialized = false
let fontsLoaded = false
let initPromise: Promise<void> | null = null

/**
 * Initialize the WASM reader module
 */
export async function initWasmReader(): Promise<void> {
  // If already initialized, return immediately
  if (initialized && wasmModule) {
    return
  }

  // If initialization is in progress, wait for it
  if (initPromise) {
    return initPromise
  }

  // Start initialization
  initPromise = (async () => {
    try {
      // Dynamic import of the WASM module
      // The path will be resolved by Vite/webpack based on build configuration
      const wasm = await import('../wasm-reader/pkg/liberty_reader')
      await wasm.default() // Initialize WASM

      wasmModule = wasm as unknown as WasmModule
      wasmModule.init()
      initialized = true

      console.log('[WasmReader] Module initialized')
    } catch (error) {
      console.error('[WasmReader] Failed to initialize:', error)
      initPromise = null // Reset so we can retry
      throw error
    }
  })()

  return initPromise
}

let fontLoadPromise: Promise<void> | null = null

/**
 * Load bundled fonts into the WASM module
 * @param forceReload - If true, reload fonts even if already loaded (needed after unloadBook)
 */
export async function loadBundledFonts(
  fonts: FontToLoad[] = DEFAULT_READER_FONTS,
  forceReload: boolean = false
): Promise<void> {
  if (fontsLoaded && !forceReload) {
    console.log('[WasmReader] Fonts already loaded, skipping')
    return
  }
  
  // If force reload requested but a load is already in progress, wait for it
  // This prevents race conditions when multiple effects call forceReload concurrently
  if (forceReload && fontLoadPromise) {
    return fontLoadPromise
  }
  
  // Reset flag if force reloading and no load in progress
  if (forceReload) {
    fontsLoaded = false
    fontLoadPromise = null
  }

  // If font loading is in progress, wait for it
  if (fontLoadPromise) {
    return fontLoadPromise
  }

  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  fontLoadPromise = (async () => {
    console.log('[WasmReader] Loading fonts:', fonts.map(f => ({ name: f.name, url: f.url })))

    let loadedCount = 0
    const errors: string[] = []

    for (const font of fonts) {
      try {
        console.log(`[WasmReader] Fetching font ${font.name} from ${font.url}`)
        const response = await fetch(font.url)
        if (!response.ok) {
          errors.push(`${font.name}: HTTP ${response.status}`)
          console.warn(`[WasmReader] Failed to load font ${font.name}: ${response.status}`)
          continue
        }

        const data = await response.arrayBuffer()
        console.log(`[WasmReader] Font ${font.name} fetched, size: ${data.byteLength} bytes`)
        
        wasmModule!.load_font(font.name, new Uint8Array(data))
        loadedCount++
        console.log(`[WasmReader] Loaded font into WASM: ${font.name}`)
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : String(error)
        errors.push(`${font.name}: ${errorMsg}`)
        console.error(`[WasmReader] Error loading font ${font.name}:`, error)
      }
    }

    if (loadedCount === 0) {
      fontLoadPromise = null // Reset so we can retry
      throw new Error(`Failed to load any fonts. Errors: ${errors.join('; ')}`)
    }

    fontsLoaded = true
    console.log(`[WasmReader] Successfully loaded ${loadedCount}/${fonts.length} fonts`)
  })()

  return fontLoadPromise
}

/**
 * Load a custom font into the WASM module
 */
export async function loadCustomFont(name: string, url: string): Promise<void> {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const response = await fetch(url)
  const data = await response.arrayBuffer()
  wasmModule.load_font(name, new Uint8Array(data))
}

// WASM-supported fonts (fonts that are bundled and loaded into WASM)
const WASM_SUPPORTED_FONTS = ['Literata']

/**
 * Map a font family to a WASM-supported font
 * WASM reader only has bundled fonts, so we need to fallback for unsupported fonts
 */
function mapToWasmFont(fontFamily: string): string {
  if (WASM_SUPPORTED_FONTS.includes(fontFamily)) {
    return fontFamily
  }
  // Fallback to default WASM font
  return 'Literata'
}

/**
 * Convert ReaderSettings to WASM format
 */
export function convertSettingsToWasm(
  settings: ReaderSettings,
  theme: ReaderTheme
): WasmReaderSettings {
  const baseSize = 16 // Base font size in pixels

  // Get theme colors
  const themeColors = WASM_THEME_COLORS[theme as WasmThemeName] || WASM_THEME_COLORS.warm

  // Map font to WASM-supported font (only Literata is bundled currently)
  const wasmFontFamily = mapToWasmFont(settings.fontFamily)

  return {
    // Typography - convert rem to pixels
    fontFamily: wasmFontFamily,
    fontSize: settings.fontSize * baseSize,
    lineHeight: settings.lineHeight,
    letterSpacing: 0, // Not currently in settings

    // Layout - convert rem/em to pixels
    paddingX: settings.contentPaddingX * baseSize,
    paddingY: settings.contentPaddingY * baseSize,
    textAlign: settings.textAlign,
    paragraphIndent: settings.paragraphIndent * settings.fontSize * baseSize,
    paragraphSpacing: settings.paragraphSpacing * settings.fontSize * baseSize,
    maxContentWidth: settings.maxContentWidth * baseSize,
    
    // Column layout
    columns: settings.columns,
    columnGap: settings.columnGap * baseSize,

    // Theme
    ...themeColors,

    // Advanced
    hyphenation: settings.hyphenation,
  }
}

/**
 * Update reader settings
 */
export function updateSettings(settings: WasmReaderSettings): WasmSettingsUpdateResult {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const rawResult = wasmModule.update_settings(JSON.stringify(settings))
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return mapToObject<WasmSettingsUpdateResult>(rawResult)
}

/**
 * Load a book into the reader
 */
export function loadBook(content: BookContent): WasmLoadBookResult {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const rawResult = wasmModule.load_book(JSON.stringify(content))
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  const result = mapToObject<WasmLoadBookResult>(rawResult)
  return result
}

/**
 * Convert a Map (from serde_wasm_bindgen) to a plain object
 */
function mapToObject<T>(mapOrObj: unknown): T {
  if (mapOrObj instanceof Map) {
    const obj: Record<string, unknown> = {}
    mapOrObj.forEach((value, key) => {
      // Recursively convert nested Maps
      obj[key] = value instanceof Map ? mapToObject(value) : value
    })
    return obj as T
  }
  return mapOrObj as T
}

/**
 * Paginate the loaded book
 */
export function paginateBook(width: number, height: number): WasmPaginationResult {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const rawResult = wasmModule.paginate(width, height)
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return mapToObject<WasmPaginationResult>(rawResult)
}

/**
 * Render a page to a pixel buffer
 */
export function renderPage(
  pageIndex: number,
  width: number,
  height: number
): Uint8ClampedArray {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const pixels = wasmModule.render_page(pageIndex, width, height)
  return new Uint8ClampedArray(pixels)
}

/**
 * Get chapter info for a page
 */
export function getPageChapter(pageIndex: number): WasmPageChapter {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const rawResult = wasmModule.get_page_chapter(pageIndex)
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return mapToObject<WasmPageChapter>(rawResult)
}

/**
 * Search for text in the book
 */
export function searchText(query: string): WasmSearchResult[] {
  if (!wasmModule) {
    throw new Error('WASM module not initialized')
  }

  const rawResult = wasmModule.search_text(query)
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  if (Array.isArray(rawResult)) {
    return rawResult.map(item => mapToObject<WasmSearchResult>(item))
  }
  return mapToObject<WasmSearchResult[]>(rawResult)
}

/**
 * Unload the current book
 */
export function unloadBook(): void {
  if (wasmModule) {
    wasmModule.unload_book()
  }
}

/**
 * Check if the WASM module is initialized
 */
export function isInitialized(): boolean {
  return initialized && wasmModule !== null
}

/**
 * Check if fonts are loaded
 */
export function areFontsLoaded(): boolean {
  return fontsLoaded
}

/**
 * Get current settings from WASM
 */
export function getCurrentSettings(): WasmReaderSettings | null {
  if (!wasmModule) {
    return null
  }

  const rawResult = wasmModule.get_settings()
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return mapToObject<WasmReaderSettings>(rawResult)
}

// ============================================================================
// Selection API
// ============================================================================

/**
 * Start text selection at a position
 */
export function selectionStart(x: number, y: number): void {
  if (wasmModule) {
    wasmModule.selection_start(x, y)
  }
}

/**
 * Update text selection during drag
 */
export function selectionUpdate(x: number, y: number): void {
  if (wasmModule) {
    wasmModule.selection_update(x, y)
  }
}

/**
 * End text selection and get the result
 */
export function selectionEnd(): WasmSelectionResult | null {
  if (!wasmModule) {
    return null
  }

  const rawResult = wasmModule.selection_end()
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return rawResult ? mapToObject<WasmSelectionResult>(rawResult) : null
}

/**
 * Clear the current selection
 */
export function selectionClear(): void {
  if (wasmModule) {
    wasmModule.selection_clear()
  }
}

/**
 * Get selection rectangles for highlighting
 */
export function getSelectionRects(): WasmSelectionRect[] {
  if (!wasmModule) {
    return []
  }

  const rawResult = wasmModule.get_selection_rects()
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  if (Array.isArray(rawResult)) {
    return rawResult.map(item => mapToObject<WasmSelectionRect>(item))
  }
  return []
}

/**
 * Get the currently selected text
 */
export function getSelectedText(): string | null {
  if (!wasmModule) {
    return null
  }

  return wasmModule.get_selected_text()
}

/**
 * Get link URL at a position (if any)
 */
export function getLinkAtPosition(
  pageIndex: number,
  x: number,
  y: number
): string | null {
  if (!wasmModule) {
    return null
  }

  return wasmModule.get_link_at_position(pageIndex, x, y)
}

// ============================================================================
// Performance API
// ============================================================================

/**
 * Pre-render pages around the current page for smoother navigation
 */
export function prerenderPages(
  currentPage: number,
  width: number,
  height: number,
  range: number = 2
): void {
  if (wasmModule) {
    wasmModule.prerender_pages(currentPage, width, height, range)
  }
}

/**
 * Get pagination statistics
 */
export function getPaginationStats(): {
  hasDocument: boolean
  isPaginated: boolean
  totalChapters: number
  totalPages: number
} | null {
  if (!wasmModule) {
    return null
  }

  const rawResult = wasmModule.get_pagination_stats()
  // FIX: Convert Map to plain object (serde_wasm_bindgen returns Maps by default)
  return mapToObject<{
    hasDocument: boolean
    isPaginated: boolean
    totalChapters: number
    totalPages: number
  }>(rawResult)
}

/**
 * Clear the render cache
 */
export function clearRenderCache(): void {
  if (wasmModule) {
    wasmModule.clear_render_cache()
  }
}

